name: devils_pyramid
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  polygon: ^0.1.0
  flutter_animate: ^4.5.2
  shared_preferences: ^2.2.2
  logger: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/fonts/

  fonts:
    - family: Lexend
      fonts:
        - asset: lib/fonts/Lexend-Thin.ttf
          weight: 100
        - asset: lib/fonts/Lexend-ExtraLight.ttf
          weight: 200
        - asset: lib/fonts/Lexend-Light.ttf
          weight: 300
        - asset: lib/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: lib/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: lib/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: lib/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: lib/fonts/Lexend-ExtraBold.ttf
          weight: 800
        - asset: lib/fonts/Lexend-Black.ttf
          weight: 900
